export const groups = [
  {
    id: '1',
    owner: 'Mario',
    subscriptionOffered: 'NowTv',
    avatar: require('../assets/avatar/mario.jpg'),
    total: 2,
    available: 1,
  },
  {
    id: '2',
    owner: 'Alice',
    subscriptionOffered: 'Netflix',
    avatar: require('../assets/avatar/alice.jpg'),
    total: 6,
    available: 5,
  },
  {
    id: ' 3',
    owner: 'Giulia',
    subscriptionOffered: 'Spotify',
    avatar: require('../assets/avatar/giulia.jpg'),
    total: 5,
    available: 1,
  },
  {
    id: '4',
    owner: 'Federica',
    subscriptionOffered: 'Disney+',
    avatar: require('../assets/avatar/federica.jpg'),
    total: 7,
    available: 1,
  },
  {
    id: '5',
    owner: 'Enrico',
    subscriptionOffered: 'Netflix',
    avatar: require('../assets/avatar/enrico.jpg'),
    total: 5,
    available: 4,
  },
  {
    id: '6',
    owner: 'Artur',
    subscriptionOffered: 'AmazonPrime',
    avatar: require('../assets/avatar/artur.jpg'),
    total: 3,
    available: null,
  },
  {
    id: '7',
    owner: 'John',
    subscriptionOffered: 'Spotify',
    avatar: require('../assets/avatar/john.jpg'),
    total: 5,
    available: 3,
  },
  {
    id: '8',
    owner: 'Federica',
    subscriptionOffered: 'Disney+',
    avatar: require('../assets/avatar/federica.jpg'),
    total: 7,
    available: 1,
  },
  {
    id: '9',
    owner: 'Enrico',
    subscriptionOffered: 'Netflix',
    avatar: require('../assets/avatar/enrico.jpg'),
    total: 5,
    available: 4,
  },
  {
    id: '10',
    owner: 'Artur',
    subscriptionOffered: 'AmazonPrime',
    avatar: require('../assets/avatar/artur.jpg'),
    total: 3,
    available: 1,
  },
  {
    id: '11',
    owner: 'John',
    subscriptionOffered: 'Spotify',
    avatar: require('../assets/avatar/john.jpg'),
    total: 5,
    available: 3,
  },
];

export const news = [
  {
    id: '1',
    title: 'NowTV arriva su Diveedi',
    date: '16.03.2021',
    image: require('../assets/news/nowtv.png'),
  },
  {
    id: '2',
    title: 'Disney+ si aggiorna con Star',
    date: '19.02.2021',
    image: require('../assets/news/disneystar.jpeg'),
  },
  {
    id: '3',
    title: 'Condividi il tuo abbonamento in palestra',
    date: '01.02.2021',
    image: require('../assets/news/gym.jpeg'),
  },
  {
    id: '4',
    title: 'Diveedi2.0 - Nuovo aggiornamento disponibile',
    date: '30.01.2021',
    image: require('../assets/news/update.jpeg'),
  },
];

export const sections = [
  {
    id: '1',
    name: 'Netflix',
    icon: require('../assets/logos/netflix.png'),
    latestReleases: [
      {
        id: '01',
        cover: require('../assets/covers/animalifantastici.jpeg'),
        title: 'Animali fantastici: I crimini di Grindelwald',
        releaseDate: '14 marzo',
      },
      {
        id: '02',
        cover: require('../assets/covers/animalifantastici.jpeg'),
        title: 'Animali fantastici: I crimini di Grindelwald',
        releaseDate: '14 marzo',
      },
      {
        id: '03',
        cover: require('../assets/covers/animalifantastici.jpeg'),
        title: 'Animali fantastici: I crimini di Grindelwald',
        releaseDate: '14 marzo',
      },
      {
        id: '04',
        cover: require('../assets/covers/animalifantastici.jpeg'),
        title: 'Animali fantastici: I crimini di Grindelwald',
        releaseDate: '14 marzo',
      },
      {
        id: '5',
        cover: require('../assets/covers/animalifantastici.jpeg'),
        title: 'Animali fantastici: I crimini di Grindelwald',
        releaseDate: '14 marzo',
      },
    ],
    backgroundColor: '#2A2A2A',
    textColor: 'white',
  },
];
